### PR TITLE
More general implementation for checkbox

### PR DESCRIPTION
**Pull request by Kapaacius**
Added local state for checkbox so one does not need to control it from the outside.
"Hidden" input is always present now so one could select it with tab also.
and multiple code style changes.

### CODE REVIEW

**Comment by ukupat** [comment]
@Kapaacius – thank you for your pull request! I really like `PropTypes.oneOf(["small", "large"])`.

**XRebel issues**
I tested the new checkbox inside of XRebel and I found out couple of issues:
- checkbox does not change the state on a first click,
- checkbox is does not have a hover style when cursor is on top of a label text.

**Keyboard geek**
I also like the "select with Tab" feature, unfortunately it is impossible to visually see that the checkbox is focused. Is it possible to make the "checkbox" border green?

**Splitting the component**
What do you think about splitting current Checkbox component into a [presentational and container components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)? This way we can reduce the component's file size and make it easier to read.

**Comment by ukupat** [comment]
@Kapaacius – why is defaultChecked property needed? I removed the property, used checked property instead (also threw away `this.props.checked === undefined`) and got the same results. Am I missing something?

**Comment by Kapaacius** [comment]
@ukupat defaultChecked is needed to to give initial value to checkbox. Thats it. If defaultChecked and checked both exists, defaultChecked is ignored. As for the other, checked===undefined exists because, when one wants to control the value from the outside through onChange fn, in that case setState is called twice...ideally this scenario shouldn't exist. Just attach onChange and read value from it (no need for checked prop).

**Comment by ukupat** [comment]
@Kapaacius – alright! Could you please resolve remaining conflicts, I will merge and publish this change after that :)

**Pull request merged**
